### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by corysimmons** [Grist/gum.js#2]
- [ ] Convert to vanilla js plugin
- [ ] Recalc width on resize
- [ ] Create various examples
- [ ] Create docs

**Comment by corysimmons** [comment]
@natebot Feel free to delete this repo if you want. I've got a local copy of it if I get time to work on it. Hope things are well with you guys.
